# Site
repository: https://github.com/BokEumEom
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 엄복음
title: 인프라 & 시스템 & 클라우드 & 데브옵스 엔지니어
email: bokmail83@gmail.com
website: https://blog.naver.com/bokmail83

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: bokeum
github_username:  bokeum
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: bokeum
linkedin_username: bokeum
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: bokeum
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
  # icon: fas fa-globe
  # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Solaris 시스템 엔지니어로 출발하여 현재는 AWS 기반의 인프라 구축 및 운영을 하고 있습니다. AWS 의 다양한 서비스를 이용하여 운영을 하고 있으며, 멀티 리전, 멀티 어카운트를 관리하고 있습니다.

  I am most skilled in: <mark>AWS</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 아데나소프트웨어
        link: https://www.adenasoft.com/
        # link_text: boringcompany.com
        sub_title: DevOps
        caption: February 2021 - Present
        quote: >
          Global Fintech
        description: | # this will include new lines to allow paragraphs
            - AWS Cloud Management and Operation
            - Terraform 도입
            - ECS 도입
            - AWS WAF 운영
            - GitLab CI / CD
            - Logs collection using CloudWatch Logs and OpenSearch
            - Apache, PHP, Kafka Installation and Configuration
            - Metabase Installation and Configuration
      - layout: left
        title: 헬로네이처
        link: https://www.hellonature.co.kr/
        # link_text: boringcompany.com
        sub_title: 시스템 엔지니어
        caption: December 2019 - November 2020
        quote: >
          온라인 유기농 신선식품 새벽배송 서비스
        description: | # this will include new lines to allow paragraphs
            - AWS Cloud Management and Operation
            - Monitoring system (cpu, mem, disk, network, etc.) using Prometheus and Grafana
            - Logs collection system (tomcat catalina, apache, nginx access, ELB, etc.) using Elastic Stack and CloudWatch Logs
            - Application monitoring system (apache, php, nodejs, tomcat) using New Relic and Pinpoint
            - AWS Resource Cost Optimization
            - Analyzing, troubleshooting, and providing solutions for technical issues.
            - Apache, Nginx, Tomcat Installation and Configuration
            - Code Build, Code Deploy
            - Yona Installation and Configuration
      - layout: left
        title: 퍼펙트월드코리아
        link: https://www.pwrd.co.kr/
        # link_text: boringcompany.com
        sub_title: 시스템 엔지니어
        caption: August 2015 - November 2019
        quote: >
          슈퍼진화스토리, 열화여가, 무신, 유니슨리그, 사조영웅전, 불패전신 모바일 게임 서비스
        description: | # this will include new lines to allow paragraphs
            - IDC Dell 130 EA management and maintenance 
            - KT U Cloud biz management and operation
            - VMware ESXi and Xen platform management and operation
            - Linux(CentOS)and Windows System engineering
            - Zabbix Monitoring System
      - layout: left
        title: 인프라닉스
        link: http://infranics.com/
        # link_text: boringcompany.com
        sub_title: 시스템 엔지니어
        caption: May 2013 - December 2014
        quote: >
          삼성 SDS 클라우드 사업팀 AWS 파트 매니지드 서비스 (챗온 등)
        description: | # this will include new lines to allow paragraphs
            - Amazon Web Service Management and Operation, Technical Support
            - EC2, EBS, S3, ELB, RDS, CLI, Ubuntu, Software Raid, Ticket, etc.
      - layout: left
        title: 유니트론씨스템즈
        link: http://www.unitrons.co.kr/
        # link_text: boringcompany.com
        sub_title: 시스템 엔지니어
        caption: April 2011 - May 2013
        quote: >
          공공기관 및 관공서 서버 구축 및 기술지원
        description: | # this will include new lines to allow paragraphs
            - Solaris Server and Storage construction and maintenance
            - Fusitsu Server and Storage maintenance 
            - Linux System maintenance
            - Windows System maintenance 
            - NetBackup Technical Support 
            - Veritas Storage Foundation 
            - Veritas Cluster Server Technical Support

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: DevOps
        link: https://blog.naver.com/bokmail83
        # link_text: boringcompany.com
        sub_title: DevOps
        caption: December 2019 - November 2020
        quote: >
          현재 업무에 사용중 혹은 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs
            - Amazon Web Services
            - Terraform
            - Linux (CentOS, Ubuntu), Windows, Solaris
            - Apache, Tomcat, Nginx, PHP
            - Docker
            - GitLab, Jenkins, Yona
            - Prometheus, Grafana, Zabbix, Nagios
            - Pinpoint, New Relic, Datadog
            - VMware ESXi, XenServer, Hyper-V
            - Elastic Stack
            - Visual Studio Code
            - NetBackup
            - Veritas Storage Foundation 
            - Veritas Cluster Server
            - Sun Microsystems(SPARC), Fujitsu, x86 Servers

  # - title: Education # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: 한경대
  #       caption: 2007 - 2018
  #       sub_title: 정보제어공학과
  #       quote: >
  #         Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
  #       description: | # this will include new lines to allow paragraphs
  #         During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Soccer
      - Watching a movie
      - Ping-pong
      - Tennis

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
